export const SET_SEARCH_INPUT_VALUE = 'SET_SEARCH_INPUT_VALUE';
export const SET_ADD_INPUT_VALUE = 'SET_ADD_INPUT_VALUE';
export const SET_IS_SORT_ENABLE = 'SET_IS_SORT_ENABLE';
export const SET_CURRENT_EDIT_TASK_ID = 'SET_CURRENT_EDIT_TASK_ID';

export const ADD_TASK = 'ADD_TASK';
export const GET_TASKS = 'GET_TASKS';
export const REMOVE_TASK = 'REMOVE_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
